// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace nsus.platform
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class address1 : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"address1\",\"namespace\":\"nsus.platform\",\"fields\":[{\"name\":" +
				"\"street\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"state\",\"type\"" +
				":\"string\"},{\"name\":\"zip\",\"type\":\"string\"}]}");
		private string _street;
		private string _city;
		private string _state;
		private string _zip;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return address1._SCHEMA;
			}
		}
		public string street
		{
			get
			{
				return this._street;
			}
			set
			{
				this._street = value;
			}
		}
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				this._state = value;
			}
		}
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				this._zip = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.street;
			case 1: return this.city;
			case 2: return this.state;
			case 3: return this.zip;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.street = (System.String)fieldValue; break;
			case 1: this.city = (System.String)fieldValue; break;
			case 2: this.state = (System.String)fieldValue; break;
			case 3: this.zip = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
