// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace nsus.platform
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class persons : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""persons"",""namespace"":""nsus.platform"",""fields"":[{""name"":""id"",""type"":""string""},{""name"":""name"",""type"":""string""},{""name"":""age"",""type"":""int""},{""name"":""address"",""type"":""string""},{""name"":""numbers"",""type"":{""type"":""array"",""items"":""string""}}]}");
		private string _id;
		private string _name;
		private int _age;
		private string _address;
		private IList<System.String> _numbers;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return persons._SCHEMA;
			}
		}
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public int age
		{
			get
			{
				return this._age;
			}
			set
			{
				this._age = value;
			}
		}
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		public IList<System.String> numbers
		{
			get
			{
				return this._numbers;
			}
			set
			{
				this._numbers = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.name;
			case 2: return this.age;
			case 3: return this.address;
			case 4: return this.numbers;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.String)fieldValue; break;
			case 1: this.name = (System.String)fieldValue; break;
			case 2: this.age = (System.Int32)fieldValue; break;
			case 3: this.address = (System.String)fieldValue; break;
			case 4: this.numbers = (IList<System.String>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
